version: '3.4'

services:
    customerdb:
        container_name: customerdb
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "SwN12345678"
            ACCEPT_EULA: "Y"

    dfds.challange.customer.api:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - "ConnectionString=Server=customerdb;Database=CustomerDb;User Id=sa;Password=SwN12345678;"
        depends_on:
            - customerdb
        ports:
            - "5000:80"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/