version: '3.4'

services:
    customerdb:
        image: mcr.microsoft.com/mssql/server

    dfds.challange.customer.api:
        image: ${DOCKER_REGISTRY-}dfdschallangecustomerapi
        build:
            context: .
            dockerfile: DFDS.Challange.Customer.Api/Dockerfile
